Add note about possible use of env variables
apache/karaf pull request #1657
Opened 2022-10-13 20:02 UTC by splatch

I found users surprised how environment variables are working with configurations. Effectively in karaf universe you need to have a configuration file first in order to override it values with environment variables. This small tweak adds explicit note for users so they do not run into wrong assumptions.

2022-10-13 20:36 UTC, mfrazier63 requested changes
Recommend slight change to wording:

"requires the OSGi configuration file (.cfg) to exist"....

"in the configuration file".....

2022-10-13 20:43 UTC, splatch commented
@mfrazier63 you're right that in most of cases it will be a cfg file, however configuration processor which does the property matching works at `ConfigurationAdmin` level which might be populated by other mechanisms. Yet, to be fair I don't know any other than one you mentioned.

2022-10-13 21:19 UTC, mfrazier63 commented
@splatch ok, no big deal if it needs to be more generic. Just wanted to make sure things were clear.

2022-10-14 13:31 UTC, jbonofre approved these changes

2022-10-14 13:31 UTC, merged