[KARAF-7754] Target Java 11
apache/karaf pull request #1781
Opened 2023-09-25 00:42 UTC by rovarga

Signed-off-by: Robert Varga <robert.varga@pantheon.tech>

2023-09-25 04:30 UTC, oscerd approved these changes

2023-12-17 06:08 UTC, jbonofre commented
It doesn't work for verify goal with this change. The verify mojo should be updated

2023-12-17 06:09 UTC, jbonofre requested changes
We need a change on the karaf-maven-plugin:verify mojo to be able to deal with Java 11 kind packages.

2023-12-18 16:16 UTC, rovarga commented
Ah, yeah, I think this needs a lot more work. I will open a new PR once we are ready to take this step.

2023-12-18 16:16 UTC, closed without merging